services:
  app:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    command: "bash"
    tty: true
    stdin_open: true
    environment:
      - PORT=4005
    ports:
      - 4005:4005
